export var states = [
    { id: "AL", name: "Alabama", foo: false},
    { id: "AZ", name: "Arizona", foo: false },
    { id: "AR", name: "Arkansas", foo: false },
    { id: "CA", name: "California", foo: false },
    { id: "CO", name: "Colorado", foo: false },
    { id: "CT", name: "Connecticut", foo: false },
    { id: "DE", name: "Delaware", foo: false },
    { id: "FL", name: "Florida", foo: false },
    { id: "GA", name: "Georgia", foo: false },
    { id: "ID", name: "Idaho", foo: false },
    { id: "IL", name: "Illinois", foo: false },
    { id: "IN", name: "Indiana", foo: false },
    { id: "IA", name: "Iowa", foo: false },
    { id: "KS", name: "Kansas", foo: false },
    { id: "KY", name: "Kentucky", foo: false },
    { id: "LA", name: "Louisiana", foo: false },
    { id: "ME", name: "Maine", foo: false },
    { id: "MD", name: "Maryland", foo: false },
    { id: "MA", name: "Massachusetts", foo: false },
    { id: "MI", name: "Michigan", foo: false },
    { id: "MN", name: "Minnesota", foo: false },
    { id: "MS", name: "Mississippi", foo: false },
    { id: "MO", name: "Missouri", foo: false },
    { id: "MT", name: "Montana", foo: false },
    { id: "NE", name: "Nebraska", foo: false },
    { id: "NV", name: "Nevada", foo: false },
    { id: "NH", name: "New Hampshire", foo: false },
    { id: "NJ", name: "New Jersey", foo: false },
    { id: "NM", name: "New Mexico", foo: false },
    { id: "NY", name: "New York", foo: false },
    { id: "NC", name: "North Carolina", foo: false },
    { id: "ND", name: "North Dakota", foo: false },
    { id: "OH", name: "Ohio", foo: false },
    { id: "OK", name: "Oklahoma", foo: false },
    { id: "OR", name: "Oregon", foo: false },
    { id: "PA", name: "Pennsylvania", foo: false },
    { id: "RI", name: "Rhode Island", foo: false },
    { id: "SC", name: "South Carolina", foo: false },
    { id: "SD", name: "South Dakota", foo: false },
    { id: "TN", name: "Tennessee", foo: false },
    { id: "TX", name: "Texas", foo: false },
    { id: "UT", name: "Utah", foo: false },
    { id: "VT", name: "Vermont", foo: false },
    { id: "VA", name: "Virginia", foo: false },
    { id: "WA", name: "Washington", foo: false },
    { id: "WV", name: "West Virginia", foo: false },
    { id: "WI", name: "Wisconsin", foo: false },
    { id: "WY", name: "Wyoming", foo: false }
  ];
  
  
